
# Por defecto, si corres la app en tu PC, usara el perfil "dev"
spring.profiles.active=dev

spring.application.name=zoomaccess

google.sheets.range=Hoja 1

# Global Jackson Configuration
spring.jackson.deserialization.fail-on-unknown-properties=false
